application:
  name: affiliateorchestration
  profile: uat2
server:
  port: :8080
service:
  -
    name: "getProductPreferenceList"
    endpoint: "https://intxgw-uat2.true.th/MGProductInfo/MGProductPreferenceInfo/getProductPreferenceList"
    system: "INTX"
    user: "ITSD_INTX"
    password: "INTXOPER1"
    connectionTimeout: 5000
    readTimeout: 15000
  -
    name: "getCPProfileByThaiID"
    endpoint: "http://hrdev/homenew/api/hr/getCPProfileByThaiID"
    system: "HR(MVP)"
    apiKey: "6144333066f3e17b3556c1952d639bf6adf7f9c4"
    apiValue: ""
    connectionTimeout: 10000
    readTimeout: 15000
